import { ArrowRight, BarChart3, Clock3, History as HistoryIcon, Plane, TrendingUp } from "lucide-react";
import { withBase } from "@/lib/baseUrl";
import SiteHeader from "@/components/SiteHeader";

const rounds = ["3,48x", "1,12x", "8,06x", "1,86x", "2,24x", "1,03x", "12,41x", "2,98x", "1,44x", "4,18x", "2,07x", "1,27x"];

export default function History() {
  return <main className="marketing-shell info-page history-page"><div className="noise-layer" aria-hidden="true" /><SiteHeader active="/history" /><section className="info-hero history-heading"><div><span className="kicker"><HistoryIcon size={14} /> LE JOURNAL DE VOL</span><h1>Chaque sortie<br /><em>laisse une trace.</em></h1><p>Utilisez l'historique pour comprendre votre rythme — pas pour courir après la dernière manche.</p></div><a className="primary-button" href={withBase("/game")}>Nouveau vol <Plane size={16} /></a></section><section className="history-overview"><div className="history-main"><div className="section-heading"><div><span className="eyebrow">MANCHES RÉCENTES</span><h2>Journal de vol en direct</h2></div><span className="history-status"><span className="pulse-dot tiny" /> Mis à jour à l'instant</span></div><div className="history-grid">{rounds.map((value, index) => <div className={`history-value ${index === 1 || index === 5 ? "danger" : ""}`} key={`${value}-${index}`}><span className="round-index">#{String(2841 - index).padStart(5, "0")}</span><strong>{value}</strong><small>{index % 3 === 0 ? "posé sans encombre" : index % 3 === 1 ? "vol terminé" : "manche complète"}</small></div>)}</div></div><aside className="history-stats"><div className="record-stat"><span className="eyebrow"><TrendingUp size={13} /> RECORD PERSO</span><strong>12,41x</strong><small>meilleur atterrissage</small></div><div className="record-stat green"><span className="eyebrow"><BarChart3 size={13} /> TAUX DE RÉUSSITE</span><strong>68,4%</strong><small>30 derniers vols</small></div><div className="record-stat"><span className="eyebrow"><Clock3 size={13} /> SORTIE MOY.</span><strong>2,16x</strong><small>votre zone idéale</small></div></aside></section><section className="history-note"><span><HistoryIcon size={17} /></span><p>L'historique éclaire, il ne garantit rien. Chaque nouvelle manche repart d'un vol vierge.</p><a className="text-link" href={withBase("/how-to-play")}>Revoir les règles <ArrowRight size={14} /></a></section><footer className="marketing-footer"><span>Chicken Crash <span className="muted-divider">•</span> Étudiez l'ascension.</span><a href={withBase("/")}>Retour à l'accueil</a></footer></main>;
}
